<script lang="ts">
  import type { PageData } from './$types';
  import { ArrowLeft, ArchiveRestore, FileText, Trash2 } from '@lucide/svelte';
  export let data: PageData;
  let notes: any[] = [...data.notes], restoring = '', toast = '';
  async function restore(id: string) { restoring = id; try { const response = await fetch(`/api/trash/${id}/restore`, { method: 'POST' }); if (!response.ok) throw new Error(); notes = notes.filter((note: any) => note.id !== id); toast = 'Note restored to workspace'; setTimeout(() => (toast = ''), 3200); } catch { toast = 'Could not restore this note'; setTimeout(() => (toast = ''), 3200); } finally { restoring = ''; } }
</script>

<svelte:head><title>Trash · Smart Note</title></svelte:head>
<main class="app-canvas min-h-screen px-5 py-8 text-slate-200 lg:px-8">{#if toast}<div role="status" class="fixed right-5 top-5 z-50 rounded-xl border border-emerald-300/20 bg-emerald-950/90 px-4 py-3 text-sm text-emerald-100 shadow-2xl">{toast}</div>{/if}<header class="shell mb-9 flex items-end justify-between"><div><p class="eyebrow">Soft deletion</p><h1 class="mt-2 text-4xl font-semibold tracking-tight text-white">Recycle bin</h1><p class="mt-2 text-sm text-slate-400">Deleted notes stay recoverable and retain their audit history.</p></div><a href="/" class="btn-secondary"><ArrowLeft size={17} /> Workspace</a></header>
  <section class="surface shell rounded-3xl p-6"><div class="mb-6 flex items-center justify-between border-b border-slate-800 pb-5"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-rose-400/10 text-rose-300"><Trash2 size={19} /></span><div><h2 class="font-semibold text-white">Deleted notes</h2><p class="text-xs text-slate-500">{notes.length} item{notes.length === 1 ? '' : 's'} available to restore</p></div></div></div>{#if !notes.length}<div class="grid min-h-64 place-items-center text-center"><div><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-800/70 text-slate-500"><ArchiveRestore size={25} /></span><h2 class="mt-4 font-semibold text-white">Nothing to recover</h2><p class="mt-2 text-sm text-slate-500">Your recycle bin is empty.</p></div></div>{:else}<div class="divide-y divide-slate-800/80">{#each notes as note}<article class="flex items-center justify-between gap-5 py-5"><div class="flex min-w-0 items-center gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-800 text-slate-400"><FileText size={18} /></span><div class="min-w-0"><p class="truncate font-medium text-white">{note.title}</p><p class="mt-1 text-xs text-slate-500">Deleted {new Date(note.deletedAt).toLocaleString()}</p></div></div><button disabled={restoring === note.id} on:click={() => restore(note.id)} class="btn-secondary shrink-0 text-sm">{restoring === note.id ? 'Restoring…' : 'Restore'} <ArchiveRestore size={16} /></button></article>{/each}</div>{/if}</section>
</main>
