<script lang="ts">
  import { ArrowLeft, FileSearch, Search, Sparkles } from '@lucide/svelte';
  let query = '', results: any[] = [], loading = false, error = '', searched = false;
  async function search() {
    const term = query.trim(); if (!term) return; loading = true; error = ''; searched = true;
    try { const response = await fetch('/api/audit/search', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query: term }) }); const body = await response.json(); if (!response.ok) { error = body.error ?? 'Không thể tìm kiếm audit'; results = []; return; } results = body.results ?? []; } catch { error = 'Không thể kết nối tới máy chủ'; results = []; } finally { loading = false; }
  }
</script>

<svelte:head><title>Audit · Smart Note</title></svelte:head>
<main class="app-canvas min-h-screen px-5 py-8 text-slate-200 lg:px-8"><header class="shell mb-9 flex items-end justify-between"><div><p class="eyebrow">Traceable by design</p><h1 class="mt-2 text-4xl font-semibold tracking-tight text-white">Audit intelligence</h1><p class="mt-2 text-sm text-slate-400">Search the verified history of your notes, permissions and changes.</p></div><a href="/" class="btn-secondary"><ArrowLeft size={17} /> Workspace</a></header>
  <div class="shell grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><section class="surface rounded-3xl p-6"><div class="flex flex-col gap-3 sm:flex-row"><label class="relative block flex-1"><Search size={18} class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" /><input bind:value={query} on:keydown={(event) => event.key === 'Enter' && search()} class="field pl-11" placeholder="Who changed Budget? Who removed the team meeting?" /></label><button class="btn-primary" disabled={loading || !query.trim()} on:click={search}>{loading ? 'Searching…' : 'Search history'} <FileSearch size={17} /></button></div>
    {#if error}<p role="alert" class="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</p>{/if}
    {#if loading}<div class="mt-6 space-y-3" aria-busy="true">{#each Array(4) as _}<div class="h-24 animate-pulse rounded-2xl bg-slate-800/60"></div>{/each}</div>{:else if results.length}<div class="mt-6 space-y-3">{#each results as item}<article class="rounded-2xl border border-slate-800 bg-slate-950/45 p-5 transition hover:border-cyan-400/30"><div class="flex items-start justify-between gap-5"><span class="rounded-lg border border-cyan-400/15 bg-cyan-400/10 px-2.5 py-1 text-xs font-bold tracking-wide text-cyan-200">{item.action}</span><time class="shrink-0 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</time></div><div class="mt-4"><p class="font-medium text-white">{item.displayName ?? item.username ?? 'Unknown user'} <span class="font-normal text-slate-500">in</span> {item.noteTitle ?? 'Deleted note'}</p><p class="mt-2 text-sm leading-6 text-slate-400">{item.searchText}</p></div></article>{/each}</div>{:else if searched}<div class="mt-12 grid place-items-center rounded-2xl border border-dashed border-slate-700 p-12 text-center"><FileSearch size={32} class="text-slate-600" /><h2 class="mt-4 font-semibold text-white">No matching events</h2><p class="mt-2 max-w-sm text-sm leading-6 text-slate-500">Try a person, note name, action, or a precise phrase from the change.</p></div>{:else}<div class="mt-12 grid place-items-center rounded-2xl border border-dashed border-slate-700 p-12 text-center"><Sparkles size={30} class="text-violet-300" /><h2 class="mt-4 font-semibold text-white">Ask your audit trail</h2><p class="mt-2 max-w-sm text-sm leading-6 text-slate-500">Searches respect your access rights and only inspect events you are allowed to view.</p></div>{/if}
  </section><aside class="surface h-fit rounded-3xl p-6"><p class="eyebrow">Examples</p><h2 class="mt-2 text-lg font-semibold text-white">Useful prompts</h2><div class="mt-5 space-y-2">{#each ['Ai sửa Budget?', 'Ai xóa task họp?', 'Minh đã sửa gì hôm qua?'] as example}<button on:click={() => { query = example; search(); }} class="w-full rounded-xl border border-slate-800 bg-slate-950/45 px-3 py-3 text-left text-sm text-slate-400 transition hover:border-violet-400/40 hover:text-violet-100">{example}</button>{/each}</div></aside></div>
</main>
