import { createHash, randomUUID } from 'node:crypto';
import { sql } from './db/postgres';
import { embedText } from './ai/gemini';

export function chunkText(value: string, size = 1200) { const clean = value.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(); const chunks: string[] = []; for (let i = 0; i < clean.length; i += size) chunks.push(clean.slice(i, i + size)); return chunks.length ? chunks : ['']; }
export async function reindexNote(noteId: string, content: string, userId: string) { const chunks = chunkText(content); await sql`DELETE FROM note_chunk WHERE note_id=${noteId}`; for (let index = 0; index < chunks.length; index++) { const text = chunks[index]; const hash = createHash('sha256').update(text).digest('hex'); const id = randomUUID(); await sql`INSERT INTO note_chunk(id,note_id,chunk_index,chunk_text,content_hash,last_updated_by) VALUES(${id},${noteId},${index},${text},${hash},${userId})`; let embedding: number[] | null = null; try { embedding = await embedText(text); } catch { } const vector = embedding ? `[${embedding.join(',')}]` : null; try { await sql`INSERT INTO note_embedding(id,chunk_id,embedding,embedding_vector,embedding_model) VALUES(${randomUUID()},${id},${embedding ? JSON.stringify(embedding) : null},${vector}::vector,${embedding ? (process.env.GEMINI_EMBEDDING_MODEL ?? 'vertex') : 'lexical-v1'})`; } catch { await sql`INSERT INTO note_embedding(id,chunk_id,embedding,embedding_model) VALUES(${randomUUID()},${id},${embedding ? JSON.stringify(embedding) : null},${embedding ? (process.env.GEMINI_EMBEDDING_MODEL ?? 'vertex') : 'lexical-v1'})`; } } }
export async function retrieveChunks(noteId: string, query: string, limit = 5) {
  let queryVector: number[] | null = null; try { queryVector = await embedText(query); } catch { }
  if (queryVector) { const vector = `[${queryVector.join(',')}]`; try { return await sql`SELECT c.id,c.chunk_text AS "chunkText",c.chunk_index AS "chunkIndex",b.id AS "blockId",1-(e.embedding_vector <=> ${vector}::vector) AS score FROM note_chunk c JOIN note_embedding e ON e.chunk_id=c.id LEFT JOIN note_block b ON b.note_id=c.note_id AND b.block_index=c.chunk_index WHERE c.note_id=${noteId} AND e.embedding_vector IS NOT NULL ORDER BY e.embedding_vector <=> ${vector}::vector LIMIT ${limit}`; } catch { } }
  const words = query.toLowerCase().split(/\W+/).filter(Boolean); const rows = await sql`SELECT c.id,c.chunk_text AS "chunkText",c.chunk_index AS "chunkIndex",b.id AS "blockId" FROM note_chunk c LEFT JOIN note_block b ON b.note_id=c.note_id AND b.block_index=c.chunk_index WHERE c.note_id=${noteId}`; return rows.map((row: any) => ({ ...row, score: words.reduce((total, word) => total + (String(row.chunkText).toLowerCase().includes(word) ? 1 : 0), 0) })).sort((a: any, b: any) => b.score - a.score).slice(0, limit);
}
